apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: dev-ns
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - image: 10.0.0.19:5000/go-rest-project-template:v0.0.1-14675a6-20220926124956
        name: app2
        ports:
        - containerPort: 8080
