apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo5
  namespace: dev-ns
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: demo5
  template:
    metadata:
      labels:
        app: demo5
    spec:
      containers:
      - image: 10.0.0.19:5000/demo5:v0.0.1-3b6f140-20220927182011
        name: demo5
        ports:
        - containerPort: 8080
