apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo2
  namespace: dev-ns
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: demo2
  template:
    metadata:
      labels:
        app: demo2
    spec:
      containers:
      - image: 10.0.0.19:5000/demo2:v0.0.1-14675a6-20220926124956
        name: demo2
        ports:
        - containerPort: 8080
