apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo2
  namespace: dev-ns
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: demo2
  template:
    metadata:
      labels:
        app: demo2
    spec:
      containers:
      - image: 192.168.112.245:5000/demo2:v0.0.1-3b6f140-20220927182011
        name: demo2
        ports:
        - containerPort: 8080
