apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo4
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: dev-ns
    server: 'https://kubernetes.default.svc'
  source:
    path: dev/applications/demo4
    repoURL: >-
      https://github.com/rdurgade/argocd-config.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - Replace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
