apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo4
  namespace: dev-ns
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: demo4
  template:
    metadata:
      labels:
        app: demo4
    spec:
      containers:
      - image: 10.0.0.19:5000/demo4:v0.0.1-3b6f140-20220927182011
        name: demo4
        ports:
        - containerPort: 8080
